# Setup
title:            Seiji Shaw
tagline:          PhD student@RRG
description:      'EECS PhD Student, MIT<br />seijis [at] mit [dot] edu<br />Office: 45-633'
url:              'https://sageshoyu.github.io' 
baseurl:          ''
paginate:         7
paginate_path:    '/blog/page:num/'

# About and contact
author:
  name:           'Seiji Shaw'

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0

permalink: /blog/:categories/:year/:month/:day/:title:output_ext

